# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt5_client_20200130.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(763, 435)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 100, 61, 16))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(110, 100, 281, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(410, 100, 31, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(440, 100, 113, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(560, 100, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(50, 130, 421, 80))
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(20, 30, 41, 20))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(70, 30, 41, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(120, 30, 31, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_4.setGeometry(QtCore.QRect(170, 30, 41, 20))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_5.setGeometry(QtCore.QRect(220, 30, 51, 20))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_6.setGeometry(QtCore.QRect(280, 30, 51, 20))
        self.radioButton_6.setObjectName("radioButton_6")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(490, 130, 141, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_7.setGeometry(QtCore.QRect(20, 30, 41, 20))
        self.radioButton_7.setChecked(True)
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_8.setGeometry(QtCore.QRect(80, 30, 41, 20))
        self.radioButton_8.setObjectName("radioButton_8")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 230, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(210, 270, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(110, 230, 93, 71))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(310, 230, 93, 71))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(490, 230, 93, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(490, 270, 93, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(60, 310, 71, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 310, 351, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(490, 310, 93, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(60, 340, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(130, 340, 461, 81))
        self.label_5.setText("")
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(50, 10, 501, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_9.setGeometry(QtCore.QRect(10, 20, 31, 20))
        self.radioButton_9.setChecked(True)
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_10.setGeometry(QtCore.QRect(50, 20, 31, 20))
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_11.setGeometry(QtCore.QRect(90, 20, 31, 20))
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_12.setGeometry(QtCore.QRect(130, 20, 31, 20))
        self.radioButton_12.setObjectName("radioButton_12")
        self.radioButton_13 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_13.setGeometry(QtCore.QRect(170, 20, 31, 20))
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_14.setGeometry(QtCore.QRect(210, 20, 31, 20))
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_15 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_15.setGeometry(QtCore.QRect(250, 20, 31, 20))
        self.radioButton_15.setObjectName("radioButton_15")
        self.radioButton_16 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_16.setGeometry(QtCore.QRect(290, 20, 31, 20))
        self.radioButton_16.setObjectName("radioButton_16")
        self.radioButton_17 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_17.setGeometry(QtCore.QRect(330, 20, 31, 20))
        self.radioButton_17.setObjectName("radioButton_17")
        self.radioButton_18 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_18.setGeometry(QtCore.QRect(370, 20, 41, 20))
        self.radioButton_18.setObjectName("radioButton_18")
        self.radioButton_19 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_19.setGeometry(QtCore.QRect(10, 50, 41, 20))
        self.radioButton_19.setObjectName("radioButton_19")
        self.radioButton_20 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_20.setGeometry(QtCore.QRect(50, 50, 41, 20))
        self.radioButton_20.setObjectName("radioButton_20")
        self.radioButton_21 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_21.setGeometry(QtCore.QRect(90, 50, 41, 20))
        self.radioButton_21.setObjectName("radioButton_21")
        self.radioButton_22 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_22.setGeometry(QtCore.QRect(130, 50, 41, 20))
        self.radioButton_22.setObjectName("radioButton_22")
        self.radioButton_23 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_23.setGeometry(QtCore.QRect(170, 50, 41, 20))
        self.radioButton_23.setObjectName("radioButton_23")
        self.radioButton_24 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_24.setGeometry(QtCore.QRect(210, 50, 41, 20))
        self.radioButton_24.setObjectName("radioButton_24")
        self.radioButton_25 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_25.setGeometry(QtCore.QRect(250, 50, 41, 20))
        self.radioButton_25.setObjectName("radioButton_25")
        self.radioButton_26 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_26.setGeometry(QtCore.QRect(290, 50, 41, 20))
        self.radioButton_26.setObjectName("radioButton_26")
        self.radioButton_27 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_27.setGeometry(QtCore.QRect(330, 50, 41, 20))
        self.radioButton_27.setObjectName("radioButton_27")
        self.radioButton_28 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_28.setGeometry(QtCore.QRect(370, 50, 41, 20))
        self.radioButton_28.setObjectName("radioButton_28")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(560, 20, 93, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(560, 60, 93, 28))
        self.pushButton_10.setObjectName("pushButton_10")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Server IP:"))
        self.lineEdit.setText(_translate("Form", "192.168.1.177"))
        self.label_2.setText(_translate("Form", "Port:"))
        self.lineEdit_2.setText(_translate("Form", "12356"))
        self.pushButton.setText(_translate("Form", "Connect"))
        self.groupBox.setTitle(_translate("Form", "Value"))
        self.radioButton.setText(_translate("Form", "20"))
        self.radioButton_2.setText(_translate("Form", "10"))
        self.radioButton_3.setText(_translate("Form", "5"))
        self.radioButton_4.setText(_translate("Form", "1"))
        self.radioButton_5.setText(_translate("Form", "0.5"))
        self.radioButton_6.setText(_translate("Form", "0.1"))
        self.groupBox_2.setTitle(_translate("Form", "Pipette"))
        self.radioButton_7.setText(_translate("Form", "a"))
        self.radioButton_8.setText(_translate("Form", "b"))
        self.pushButton_2.setText(_translate("Form", "Back"))
        self.pushButton_3.setText(_translate("Form", "Forward"))
        self.pushButton_4.setText(_translate("Form", "Left"))
        self.pushButton_5.setText(_translate("Form", "Right"))
        self.pushButton_6.setText(_translate("Form", "Up"))
        self.pushButton_7.setText(_translate("Form", "Down"))
        self.label_3.setText(_translate("Form", "Command:"))
        self.pushButton_8.setText(_translate("Form", "Send"))
        self.label_4.setText(_translate("Form", "Response:"))
        self.groupBox_3.setTitle(_translate("Form", "Slot"))
        self.radioButton_9.setText(_translate("Form", "1"))
        self.radioButton_10.setText(_translate("Form", "2"))
        self.radioButton_11.setText(_translate("Form", "3"))
        self.radioButton_12.setText(_translate("Form", "4"))
        self.radioButton_13.setText(_translate("Form", "5"))
        self.radioButton_14.setText(_translate("Form", "6"))
        self.radioButton_15.setText(_translate("Form", "7"))
        self.radioButton_16.setText(_translate("Form", "8"))
        self.radioButton_17.setText(_translate("Form", "9"))
        self.radioButton_18.setText(_translate("Form", "10"))
        self.radioButton_19.setText(_translate("Form", "11"))
        self.radioButton_20.setText(_translate("Form", "12"))
        self.radioButton_21.setText(_translate("Form", "13"))
        self.radioButton_22.setText(_translate("Form", "14"))
        self.radioButton_23.setText(_translate("Form", "15"))
        self.radioButton_24.setText(_translate("Form", "16"))
        self.radioButton_25.setText(_translate("Form", "17"))
        self.radioButton_26.setText(_translate("Form", "18"))
        self.radioButton_27.setText(_translate("Form", "19"))
        self.radioButton_28.setText(_translate("Form", "20"))
        self.pushButton_9.setText(_translate("Form", "Load"))
        self.pushButton_10.setText(_translate("Form", "Save"))
